github.com:
    users:
        SebastianVernisMora:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: SebastianVernisMora
